sudo: required
services:
    - docker

before _install:
    - docker build -t beastlee23/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true beastlee23/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "Docker-react-env"
    bucket_name: "elasticbeanstalk-us-west-2-<some number>"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"